#!/usr/bin/env python3
"""Hydraulic diffusivity: this project's arms against Wang & Dunham's.

EVERY NUMBER IS PARSED FROM SOURCE, not transcribed. Taiyi's come out of
~/3dhbi/taiyi-wang-seis3D by regex, ours out of the decks in
grid_search_inputs. If either changes, this table changes with it, and if a
value cannot be found the script fails instead of falling back on a literal.

WHY IT EXISTS. I answered "is my diffusivity the same as Taiyi's?" with
D = 7.865 m^2/s, computed from `k = 7e-13` at setup_model.m:95. That scalar is
commented "from trial and error" and is a repo default. THE PAPER'S CALIBRATED
FAULT ZONE IS TWO-ZONE -- Table 1, k = 1.1e-12 within 150 m of the well and
4e-13 beyond -- applied in injection2.m:69-75 when M2.k is a function handle,
and constructed in export_panelA.m:32-34. Using the scalar gave a single
diffusivity that happened to sit between his two and made arm 2 look like a
match to within 11%. It is not a match, and the conclusion drawn from it was
withdrawn.

    D = k / (eta * phi * beta)

phi and beta appear only as their product in the governing equations, which
setup_model.m:101 notes explicitly, so neither is separately identifiable from
a pressure record.

WHAT THE COMPARISON ACTUALLY SHOWS. Near the well the two models are within
30%. In the far field they differ by a factor of 128, because Taiyi's zone is a
2.75x step and ours is a 250x step. The structural difference between the
models is the CONTRAST, not the viscosity and not the near-well value.

Usage:  python diffusivity_table.py
"""
import re
from pathlib import Path

TAIYI = Path("/home/users/nberrios/3dhbi/taiyi-wang-seis3D")
IN = Path("/home/groups/edunham/nberrios/3dhbi/examples/grid_search_inputs")
OUT = Path("/home/users/nberrios/3dhbi/hbi_git/docs/figs/cycle2/DIFFUSIVITY.md")

# model-free, from docs/postshutin/classic_front_fit.py
D_TRIG, D_BACK = 0.102, 0.154

ARMS = {1: 632950, 2: 632960, 3: 632970, 4: 632980}


def grab(path, pattern, what):
    """First regex group in `path`, or a hard failure naming what was missing."""
    txt = (TAIYI / path).read_text()
    m = re.search(pattern, txt, re.M)
    if not m:
        raise SystemExit(f"{path}: could not find {what} via {pattern!r}")
    return float(m.group(1)), f"{path}:{txt[:m.start()].count(chr(10)) + 1}"


def deck(n):
    out = {}
    for line in (IN / f"res{n}.in").read_text().splitlines():
        if line.startswith("!") or not line.strip():
            continue
        w = line.split()
        if len(w) >= 2:
            out[w[0]] = " ".join(w[1:])
    return out


def ff(x):
    return float(str(x).replace("d", "e").replace("D", "e"))


def main(argv=None):
    eta_t, src_eta = grab("source_code/setup_model.m",
                          r"^eta_v\s*=\s*([0-9.eE+-]+)", "eta_v")
    phi_t, src_phi = grab("source_code/setup_model.m",
                          r"^phi\s*=\s*([0-9.eE+-]+)", "phi")
    bet_t, src_bet = grab("source_code/setup_model.m",
                          r"^beta\s*=\s*([0-9.eE+-]+)", "beta")
    k_sc, src_ksc = grab("source_code/setup_model.m",
                         r"^k\s*=\s*([0-9.eE+-]+)", "the scalar k")
    k_near, src_kn = grab("projects/export_panelA.m",
                          r"^k_near\s*=\s*([0-9.eE+-]+)", "k_near")
    k_far, src_kf = grab("projects/diag_k_profile.m",
                         r"k_far\s*=\s*([0-9.eE+-]+)", "k_far")
    r_k, src_rk = grab("projects/export_panelA.m",
                       r"^r_k\s*=\s*([0-9.eE+-]+)", "r_k")
    den_t = eta_t * phi_t * bet_t

    L = ["# Hydraulic diffusivity: this project against Wang & Dunham\n",
         "Generated by `docs/cooper_basin/diffusivity_table.py`, which parses "
         "every value out of source rather than transcribing it.\n",
         "\n## The formula\n",
         "```\nD = k / (eta * phi * beta)\n```\n",
         "`phi` and `beta` enter the governing equations only as their "
         "product (`setup_model.m:101` says so explicitly), so neither is "
         "separately identifiable from a pressure record.\n",
         "\n## Wang & Dunham\n",
         "| quantity | value | source |", "|---|---|---|",
         f"| `eta_v` | {eta_t:.3e} Pa s | `{src_eta}` |",
         f"| `phi` | {phi_t:.0e} | `{src_phi}` |",
         f"| `beta` | {bet_t:.0e} 1/Pa | `{src_bet}` |",
         f"| denominator | {den_t:.4e} | |",
         f"| `k_near`, r <= {r_k:.0f} m | {k_near:.2e} m^2 | `{src_kn}` |",
         f"| `k_far`, r > {r_k:.0f} m | {k_far:.2e} m^2 | `{src_kf}` |",
         "",
         f"    D_near = {k_near:.2e} / {den_t:.4e} = {k_near/den_t:.3f} m^2/s",
         f"    D_far  = {k_far:.2e} / {den_t:.4e} = {k_far/den_t:.3f} m^2/s",
         f"    contrast k_near/k_far = {k_near/k_far:.2f}x",
         "",
         f"**Not** the scalar `k = {k_sc:.0e}` at `{src_ksc}`, which is "
         f"commented *\"from trial and error\"* and would give "
         f"{k_sc/den_t:.3f} m^2/s. That is a repo default; Table 1's "
         f"calibrated fault zone is the two-zone profile above, applied at "
         f"`injection2.m:69-75` when `M2.k` is a function handle. An earlier "
         f"version of this comparison used the scalar and concluded that arm 2 "
         f"matched Taiyi to 11%. It does not; that conclusion is withdrawn.\n",
         "\n## This project\n",
         "| arm | run | eta Pa s | phi*beta 1/Pa | kpmax m^2 | kpmin m^2 | "
         "D near | D far | contrast |", "|---|---|---|---|---|---|---|---|---|"]

    rows = {}
    for arm, n in ARMS.items():
        d = deck(n)
        eta, pb = ff(d["eta"]), ff(d["phi"]) * ff(d["beta"])
        kx, km = ff(d["kpmax"]), ff(d["kpmin"])
        den = eta * pb
        rows[arm] = (kx / den, km / den)
        L.append(f"| {arm} | {n} | {eta:.3e} | {pb:.3e} | {kx:.2e} | "
                 f"{km:.2e} | {kx/den:.3f} | {km/den:.4f} | {kx/km:.0f}x |")
    L.append("\nThe disc radius is a separate key (`parameter_file`); arm 2's "
             "was 300 m and the running grid spans 150-450 m, against Taiyi's "
             f"{r_k:.0f} m.\n")

    L += ["\n## Side by side, arm 2 against Table 1\n",
          "| | Taiyi | arm 2 | ratio |", "|---|---|---|---|",
          f"| near-well D | {k_near/den_t:.3f} | {rows[2][0]:.3f} | "
          f"{rows[2][0]/(k_near/den_t):.3f}x |",
          f"| **far-field D** | **{k_far/den_t:.3f}** | **{rows[2][1]:.4f}** | "
          f"**1/{(k_far/den_t)/rows[2][1]:.0f}** |",
          f"| contrast | {k_near/k_far:.2f}x | 250x | |",
          f"| zone radius | {r_k:.0f} m | 300 m | |",
          "",
          "Near the well the two models agree to 30%. The far field differs by "
          "a factor of 128, and the reason is the CONTRAST: Taiyi's fault zone "
          "is a 2.75x step, ours is 250x. That is the structural difference "
          "between the models -- not the viscosity, and not the near-well "
          "value.\n"]

    L += ["\n## Against the seismicity\n",
          "Model-free diffusivities fitted to the event cloud, from "
          "`docs/postshutin/classic_front_fit.py`: **"
          f"{D_TRIG:.3f}** m^2/s from the triggering front and **{D_BACK:.3f}**"
          " from the back front. Neither depends on any simulation.\n",
          "| | D m^2/s | vs back-front D |", "|---|---|---|",
          f"| Taiyi near-well | {k_near/den_t:.3f} | {(k_near/den_t)/D_BACK:.1f}x |",
          f"| Taiyi far field | {k_far/den_t:.3f} | {(k_far/den_t)/D_BACK:.1f}x |",
          f"| arm 2 disc | {rows[2][0]:.3f} | {rows[2][0]/D_BACK:.1f}x |",
          f"| **arm 2 background** | **{rows[2][1]:.4f}** | "
          f"**{rows[2][1]/D_BACK:.2f}x** |",
          "",
          "Taiyi's far field is 29x the back-front diffusivity. Arm 2's "
          "background is 0.23x it -- the only value in either model within a "
          "factor of five of what the seismicity implies. Arm 2's disc is 57x "
          "it, so the model spans the observation rather than matching it "
          "anywhere.\n",
          "\n### The caveat that belongs with this\n",
          "A diffusivity fitted to a triggering front is convention-dependent: "
          "the same envelope under r = sqrt(4Dt) rather than sqrt(4 pi D t) "
          "gives a D that is pi times larger. Shapiro (2000) calls the step "
          "that produces the 4 pi \"of partially heuristic character\". The "
          "back-front 4D is derived rather than conventional, which is why "
          f"{D_BACK:.3f} is used as the reference above. Even with a factor of "
          "pi either way, the ordering here does not change.\n"]

    txt = "\n".join(L) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(txt)
    print(txt)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
